/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Doctors */
        get: operations["list_doctors_api_doctors_get"];
        put?: never;
        /** Create Doctor */
        post: operations["create_doctor_api_doctors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/{doctor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctor */
        get: operations["get_doctor_api_doctors__doctor_id__get"];
        put?: never;
        post?: never;
        /** Delete Doctor */
        delete: operations["delete_doctor_api_doctors__doctor_id__delete"];
        options?: never;
        head?: never;
        /** Update Doctor */
        patch: operations["update_doctor_api_doctors__doctor_id__patch"];
        trace?: never;
    };
    "/api/doctors/{doctor_id}/employment-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Employment Period */
        post: operations["create_employment_period_api_doctors__doctor_id__employment_periods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/{doctor_id}/qualifications/{qualification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Qualification */
        post: operations["add_qualification_api_doctors__doctor_id__qualifications__qualification_id__post"];
        /** Remove Qualification */
        delete: operations["remove_qualification_api_doctors__doctor_id__qualifications__qualification_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employment-periods/{ep_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Employment Period */
        delete: operations["delete_employment_period_api_employment_periods__ep_id__delete"];
        options?: never;
        head?: never;
        /** Update Employment Period */
        patch: operations["update_employment_period_api_employment_periods__ep_id__patch"];
        trace?: never;
    };
    "/api/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Departments */
        get: operations["list_departments_api_departments_get"];
        put?: never;
        /** Create Department */
        post: operations["create_department_api_departments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/departments/{department_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Department */
        get: operations["get_department_api_departments__department_id__get"];
        put?: never;
        post?: never;
        /** Delete Department */
        delete: operations["delete_department_api_departments__department_id__delete"];
        options?: never;
        head?: never;
        /** Update Department */
        patch: operations["update_department_api_departments__department_id__patch"];
        trace?: never;
    };
    "/api/shift-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shift Types */
        get: operations["list_shift_types_api_shift_types_get"];
        put?: never;
        /** Create Shift Type */
        post: operations["create_shift_type_api_shift_types_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shift-types/{shift_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shift Type */
        get: operations["get_shift_type_api_shift_types__shift_type_id__get"];
        put?: never;
        post?: never;
        /** Delete Shift Type */
        delete: operations["delete_shift_type_api_shift_types__shift_type_id__delete"];
        options?: never;
        head?: never;
        /** Update Shift Type */
        patch: operations["update_shift_type_api_shift_types__shift_type_id__patch"];
        trace?: never;
    };
    "/api/qualifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Qualifications */
        get: operations["list_qualifications_api_qualifications_get"];
        put?: never;
        /** Create Qualification */
        post: operations["create_qualification_api_qualifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/qualifications/{qualification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Qualification */
        get: operations["get_qualification_api_qualifications__qualification_id__get"];
        put?: never;
        post?: never;
        /** Delete Qualification */
        delete: operations["delete_qualification_api_qualifications__qualification_id__delete"];
        options?: never;
        head?: never;
        /** Update Qualification */
        patch: operations["update_qualification_api_qualifications__qualification_id__patch"];
        trace?: never;
    };
    "/api/rule-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rule Overrides */
        get: operations["list_rule_overrides_api_rule_overrides_get"];
        put?: never;
        /** Create Rule Override */
        post: operations["create_rule_override_api_rule_overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rule-overrides/{override_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rule Override */
        get: operations["get_rule_override_api_rule_overrides__override_id__get"];
        put?: never;
        post?: never;
        /** Delete Rule Override */
        delete: operations["delete_rule_override_api_rule_overrides__override_id__delete"];
        options?: never;
        head?: never;
        /** Update Rule Override */
        patch: operations["update_rule_override_api_rule_overrides__override_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DepartmentCreate */
        DepartmentCreate: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
            /**
             * Is Shift Relevant
             * @default true
             */
            is_shift_relevant: boolean;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
            /** Notes */
            notes?: string | null;
        };
        /** DepartmentResponse */
        DepartmentResponse: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
            /**
             * Is Shift Relevant
             * @default true
             */
            is_shift_relevant: boolean;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DepartmentUpdate */
        DepartmentUpdate: {
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Is External */
            is_external?: boolean | null;
            /** Is Shift Relevant */
            is_shift_relevant?: boolean | null;
            /** Active */
            active?: boolean | null;
            /** Display Order */
            display_order?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** DoctorCreate */
        DoctorCreate: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** @default INTERNAL */
            doctor_type: components["schemas"]["DoctorType"];
            /** Weiterbildungsjahr */
            weiterbildungsjahr?: number | null;
            /**
             * Is Facharzt
             * @default false
             */
            is_facharzt: boolean;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Notes */
            notes?: string | null;
        };
        /**
         * DoctorQualificationBody
         * @description Optionaler Body für die Qualifikations-Zuweisung (Pfad liefert IDs).
         */
        DoctorQualificationBody: {
            /** Acquired At */
            acquired_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** DoctorQualificationResponse */
        DoctorQualificationResponse: {
            /** Doctor Id */
            doctor_id: number;
            /** Qualification Id */
            qualification_id: number;
            /** Acquired At */
            acquired_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DoctorResponse */
        DoctorResponse: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** @default INTERNAL */
            doctor_type: components["schemas"]["DoctorType"];
            /** Weiterbildungsjahr */
            weiterbildungsjahr?: number | null;
            /**
             * Is Facharzt
             * @default false
             */
            is_facharzt: boolean;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DoctorType
         * @enum {string}
         */
        DoctorType: "INTERNAL" | "EXTERNAL";
        /** DoctorUpdate */
        DoctorUpdate: {
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            doctor_type?: components["schemas"]["DoctorType"] | null;
            /** Weiterbildungsjahr */
            weiterbildungsjahr?: number | null;
            /** Is Facharzt */
            is_facharzt?: boolean | null;
            /** Active */
            active?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** DoctorWithRelations */
        DoctorWithRelations: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** @default INTERNAL */
            doctor_type: components["schemas"]["DoctorType"];
            /** Weiterbildungsjahr */
            weiterbildungsjahr?: number | null;
            /**
             * Is Facharzt
             * @default false
             */
            is_facharzt: boolean;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Employment Periods
             * @default []
             */
            employment_periods: components["schemas"]["EmploymentPeriodResponse"][];
            /**
             * Qualifications
             * @default []
             */
            qualifications: components["schemas"]["QualificationResponse"][];
        };
        /**
         * EmploymentPeriodBody
         * @description Request-Body für POST/PATCH wenn doctor_id aus dem Pfad kommt.
         */
        EmploymentPeriodBody: {
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Employment Percentage */
            employment_percentage: number;
            /** Notes */
            notes?: string | null;
        };
        /** EmploymentPeriodResponse */
        EmploymentPeriodResponse: {
            /** Doctor Id */
            doctor_id: number;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Employment Percentage */
            employment_percentage: number;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EmploymentPeriodUpdate */
        EmploymentPeriodUpdate: {
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Employment Percentage */
            employment_percentage?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * OverrideScope
         * @enum {string}
         */
        OverrideScope: "GLOBAL" | "DOCTOR";
        /** QualificationCreate */
        QualificationCreate: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** QualificationResponse */
        QualificationResponse: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** QualificationUpdate */
        QualificationUpdate: {
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Description */
            description?: string | null;
            /** Active */
            active?: boolean | null;
        };
        /** RuleOverrideCreate */
        RuleOverrideCreate: {
            /** Rule Key */
            rule_key: string;
            /** @default GLOBAL */
            scope: components["schemas"]["OverrideScope"];
            /** Doctor Id */
            doctor_id?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Override Value */
            override_value: string;
            /** Reason */
            reason?: string | null;
        };
        /** RuleOverrideResponse */
        RuleOverrideResponse: {
            /** Rule Key */
            rule_key: string;
            /** @default GLOBAL */
            scope: components["schemas"]["OverrideScope"];
            /** Doctor Id */
            doctor_id?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Override Value */
            override_value: string;
            /** Reason */
            reason?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RuleOverrideUpdate */
        RuleOverrideUpdate: {
            /** Rule Key */
            rule_key?: string | null;
            scope?: components["schemas"]["OverrideScope"] | null;
            /** Doctor Id */
            doctor_id?: number | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Override Value */
            override_value?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** ShiftTypeCreate */
        ShiftTypeCreate: {
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /**
             * Applies On Weekdays
             * @default true
             */
            applies_on_weekdays: boolean;
            /**
             * Applies On Weekend
             * @default false
             */
            applies_on_weekend: boolean;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** ShiftTypeResponse */
        ShiftTypeResponse: {
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /**
             * Applies On Weekdays
             * @default true
             */
            applies_on_weekdays: boolean;
            /**
             * Applies On Weekend
             * @default false
             */
            applies_on_weekend: boolean;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /**
             * Display Order
             * @default 0
             */
            display_order: number;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ShiftTypeUpdate */
        ShiftTypeUpdate: {
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            /** Applies On Weekdays */
            applies_on_weekdays?: boolean | null;
            /** Applies On Weekend */
            applies_on_weekend?: boolean | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Display Order */
            display_order?: number | null;
            /** Active */
            active?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_doctors_api_doctors_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorWithRelations"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_doctor_api_doctors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doctor_api_doctors__doctor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorWithRelations"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_doctor_api_doctors__doctor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_doctor_api_doctors__doctor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employment_period_api_doctors__doctor_id__employment_periods_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmploymentPeriodBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmploymentPeriodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_qualification_api_doctors__doctor_id__qualifications__qualification_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DoctorQualificationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorQualificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_qualification_api_doctors__doctor_id__qualifications__qualification_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_employment_period_api_employment_periods__ep_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ep_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employment_period_api_employment_periods__ep_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ep_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmploymentPeriodUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmploymentPeriodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_departments_api_departments_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_department_api_departments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_department_api_departments__department_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_department_api_departments__department_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_department_api_departments__department_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                department_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shift_types_api_shift_types_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftTypeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shift_type_api_shift_types_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftTypeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftTypeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shift_type_api_shift_types__shift_type_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftTypeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shift_type_api_shift_types__shift_type_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_type_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shift_type_api_shift_types__shift_type_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_type_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftTypeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftTypeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_qualifications_api_qualifications_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualificationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_qualification_api_qualifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualificationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_qualification_api_qualifications__qualification_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_qualification_api_qualifications__qualification_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_qualification_api_qualifications__qualification_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualificationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rule_overrides_api_rule_overrides_get: {
        parameters: {
            query?: {
                scope?: components["schemas"]["OverrideScope"] | null;
                doctor_id?: number | null;
                rule_key?: string | null;
                active_on_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOverrideResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_override_api_rule_overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleOverrideCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOverrideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_override_api_rule_overrides__override_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                override_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOverrideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_override_api_rule_overrides__override_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                override_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_override_api_rule_overrides__override_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                override_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleOverrideUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOverrideResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
