/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Doctors */
        get: operations["list_doctors_api_doctors_get"];
        put?: never;
        /** Create Doctor */
        post: operations["create_doctor_api_doctors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/{doctor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Doctor */
        get: operations["get_doctor_api_doctors__doctor_id__get"];
        put?: never;
        post?: never;
        /** Delete Doctor */
        delete: operations["delete_doctor_api_doctors__doctor_id__delete"];
        options?: never;
        head?: never;
        /** Update Doctor */
        patch: operations["update_doctor_api_doctors__doctor_id__patch"];
        trace?: never;
    };
    "/api/doctors/{doctor_id}/employment-periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Employment Period */
        post: operations["create_employment_period_api_doctors__doctor_id__employment_periods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/{doctor_id}/qualifications/{qualification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Qualification */
        post: operations["add_qualification_api_doctors__doctor_id__qualifications__qualification_id__post"];
        /** Remove Qualification */
        delete: operations["remove_qualification_api_doctors__doctor_id__qualifications__qualification_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employment-periods/{ep_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Employment Period */
        delete: operations["delete_employment_period_api_employment_periods__ep_id__delete"];
        options?: never;
        head?: never;
        /** Update Employment Period */
        patch: operations["update_employment_period_api_employment_periods__ep_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DoctorCreate */
        DoctorCreate: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** @default INTERNAL */
            doctor_type: components["schemas"]["DoctorType"];
            /** Weiterbildungsjahr */
            weiterbildungsjahr?: number | null;
            /**
             * Is Facharzt
             * @default false
             */
            is_facharzt: boolean;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Notes */
            notes?: string | null;
        };
        /**
         * DoctorQualificationBody
         * @description Optionaler Body für die Qualifikations-Zuweisung (Pfad liefert IDs).
         */
        DoctorQualificationBody: {
            /** Acquired At */
            acquired_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** DoctorQualificationResponse */
        DoctorQualificationResponse: {
            /** Doctor Id */
            doctor_id: number;
            /** Qualification Id */
            qualification_id: number;
            /** Acquired At */
            acquired_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DoctorResponse */
        DoctorResponse: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** @default INTERNAL */
            doctor_type: components["schemas"]["DoctorType"];
            /** Weiterbildungsjahr */
            weiterbildungsjahr?: number | null;
            /**
             * Is Facharzt
             * @default false
             */
            is_facharzt: boolean;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DoctorType
         * @enum {string}
         */
        DoctorType: "INTERNAL" | "EXTERNAL";
        /** DoctorUpdate */
        DoctorUpdate: {
            /** Name */
            name?: string | null;
            /** Short Name */
            short_name?: string | null;
            doctor_type?: components["schemas"]["DoctorType"] | null;
            /** Weiterbildungsjahr */
            weiterbildungsjahr?: number | null;
            /** Is Facharzt */
            is_facharzt?: boolean | null;
            /** Active */
            active?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** DoctorWithRelations */
        DoctorWithRelations: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** @default INTERNAL */
            doctor_type: components["schemas"]["DoctorType"];
            /** Weiterbildungsjahr */
            weiterbildungsjahr?: number | null;
            /**
             * Is Facharzt
             * @default false
             */
            is_facharzt: boolean;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Employment Periods
             * @default []
             */
            employment_periods: components["schemas"]["EmploymentPeriodResponse"][];
            /**
             * Qualifications
             * @default []
             */
            qualifications: components["schemas"]["QualificationResponse"][];
        };
        /**
         * EmploymentPeriodBody
         * @description Request-Body für POST/PATCH wenn doctor_id aus dem Pfad kommt.
         */
        EmploymentPeriodBody: {
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Employment Percentage */
            employment_percentage: number;
            /** Notes */
            notes?: string | null;
        };
        /** EmploymentPeriodResponse */
        EmploymentPeriodResponse: {
            /** Doctor Id */
            doctor_id: number;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Employment Percentage */
            employment_percentage: number;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** EmploymentPeriodUpdate */
        EmploymentPeriodUpdate: {
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Employment Percentage */
            employment_percentage?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** QualificationResponse */
        QualificationResponse: {
            /** Name */
            name: string;
            /** Short Name */
            short_name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_doctors_api_doctors_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorWithRelations"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_doctor_api_doctors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doctor_api_doctors__doctor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorWithRelations"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_doctor_api_doctors__doctor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_doctor_api_doctors__doctor_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_employment_period_api_doctors__doctor_id__employment_periods_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmploymentPeriodBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmploymentPeriodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_qualification_api_doctors__doctor_id__qualifications__qualification_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DoctorQualificationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorQualificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_qualification_api_doctors__doctor_id__qualifications__qualification_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctor_id: number;
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_employment_period_api_employment_periods__ep_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ep_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_employment_period_api_employment_periods__ep_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ep_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmploymentPeriodUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmploymentPeriodResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
